<a href="https://colab.research.google.com/github/sanu1230/Academic-Assignments/blob/master/Tensorflow_Basic_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Basics of Tensorflow

In [ ]:
%tensorflow_version 2.x

In [ ]:
# Import package
import tensorflow as tf
print(tf.__version__)

2.3.0


In [ ]:
# Create a Tensor.
hello = tf.constant("hello world")
print(hello)

tf.Tensor(b'hello world', shape=(), dtype=string)


In [ ]:
# Define tensor constants.
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(5)

In [ ]:
print('', a, '\n', b, '\n', c)

 tf.Tensor(2, shape=(), dtype=int32) 
 tf.Tensor(3, shape=(), dtype=int32) 
 tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
# Basic arithmetic operations
add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)

In [ ]:
# Access tensors value.
print("add =", add.numpy())
print("sub =", sub.numpy())
print("mul =", mul.numpy())
print("div =", div.numpy())

add = 5
sub = -1
mul = 6
div = 0.6666666666666666


In [ ]:
# Matrix multiplications.
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[5., 6.], [7., 8.]])

product = tf.matmul(matrix1, matrix2)

In [ ]:
product

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float32)>

In [ ]:
# Convert Tensor to Numpy.
product.numpy()

array([[19., 22.],
       [43., 50.]], dtype=float32)